version: "3"
services:

  fastapi_server:
    build:
      context: .
      dockerfile: ./src/Dockerfile.dev
    env_file:
      - .env
    container_name: ${PROJECT_NAME}_fastapi_server
    # ports:
    #   - "${SERVER_PORT}:8000"
    volumes:
      - ./src/api:/app
    depends_on:
      # - redis_server
      - database
  
  database:
    image: bitnami/postgresql:13.3.0
    restart: always
    container_name: ${PROJECT_NAME}_database
    env_file: ".env"
    user: root
    volumes:
      - ./db_docker:/bitnami/postgresql
      - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
    ports:
      - 5432:5432 # Remove this on production
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD="trust"

  caddy_reverse_proxy:
    container_name: ${PROJECT_NAME}_caddy_reverse_proxy
    image: caddy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./src/static:/static
      - caddy_data:/data
      - caddy_config:/config

  # redis_server:
  #   image: redis:alpine
  #   container_name: ${PROJECT_NAME}_redis_server    
  #   restart: always
  #   expose:
  #     - 6379
  #   env_file: .env

  # celery_worker:
  #   container_name: celery_worker
  #   restart: always
  #   build:
  #     context: ./src    
  #     args:
  #       INSTALL_DEV: ${INSTALL_DEV-false}
  #   command: "watchfiles 'celery -A app.core.celery worker -l info' "
  #   volumes:
  #     - ./backend/app:/code
  #   depends_on:
  #     - database
  #     - redis_server
  #   env_file: .env
  
  # celery_beat: 
  #   container_name: celery_beat
  #   restart: always
  #   build:
  #     context: ./backend
  #     args:
  #       INSTALL_DEV: ${INSTALL_DEV-false}
  #   command: celery -A app.core.celery beat -l info -S celery_sqlalchemy_scheduler.schedulers:DatabaseScheduler -l info
  #   volumes:
  #     - ./backend/app:/code
  #   depends_on:
  #     - database
  #     - redis_server
  #   env_file: .env

  # to add metrics view this link:
  # https://habr.com/ru/companies/slurm/articles/741670/

volumes:
  caddy_data:
  caddy_config:

